[package]
name = "egui-winit"
version = "0.36.2"
edition = "2024"
description = "Internal patch shim that re-exports functora-egui-winit as egui-winit for eframe"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/functora/functora.github.io/tree/master/rust/egui-winit"
documentation = "https://docs.rs/functora-egui-winit"

[lib]
name = "egui_winit"
path = "src/lib.rs"

[dependencies]
functora-egui-winit = { version = "0.36.2", path = "../functora-egui-winit" }

[features]
default = ["functora-egui-winit/default"]
accesskit = ["functora-egui-winit/accesskit"]
android-game-activity = ["functora-egui-winit/android-game-activity"]
android-native-activity = ["functora-egui-winit/android-native-activity"]
bytemuck = ["functora-egui-winit/bytemuck"]
clipboard = ["functora-egui-winit/clipboard"]
links = ["functora-egui-winit/links"]
serde = ["functora-egui-winit/serde"]
wayland = ["functora-egui-winit/wayland"]
x11 = ["functora-egui-winit/x11"]

[lints.rust]
unused_results = "warn"
[lints.clippy]
pedantic = "warn"
# strict
or_fun_call = "warn"
must_use_unit = "warn"
ignored_unit_patterns = "warn"
let_underscore_must_use = "warn"
map_unwrap_or = "warn"
unwrap_used = "warn"
expect_used = "warn"
shadow_same = "warn"
shadow_reuse = "warn"
shadow_unrelated = "warn"
# relaxed
similar_names = { level = "allow", priority = 1 }
too_many_lines = { level = "allow", priority = 1 }
wildcard_imports = { level = "allow", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }
semicolon_if_nothing_returned = { level = "allow", priority = 1 }
