name:                warp-grpc
version:             0.4.0.1
github:              "haskell-grpc-native/http2-grpc-haskell"
license:             BSD3
author:              "Lucas DiCioccio, Alejandro Serrano"
maintainer:          "lucas@dicioccio.fr"
copyright:           "2017 - 2020 Lucas DiCioccio, Alejandro Serrano"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A minimal gRPC server on top of Warp.
category:            Networking

description:         Please see the README on Github at <https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/master/warp-grpc/README.md>

dependencies:
- base >= 4.10 && < 5
- async >= 2.2.1 && < 3
- binary >= 0.8.5 && < 0.9
- bytestring >= 0.10.8 && < 0.11
- case-insensitive >= 1.2.0 && < 1.3
- http2 >= 1.6 && < 3.1
- http2-grpc-types >= 0.5 && < 0.6
- http-types >= 0.12 && < 0.13
- unliftio-core >= 0.1 && < 0.3
- wai >= 3.2 && < 3.4
- warp >= 3.2.23 && < 3.4
- warp-tls >= 3.2 && < 3.4

library:
  source-dirs: src
  ghc-options: -Wall
