# Choose a build environment
dist: bionic

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

jobs:
  fast_finish: true
  include:
    - name: "Stackage 18.x"
      script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-18.yaml
      install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-18.yaml
    - name: "Stackage 17.x"
      script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-17.yaml
      install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-17.yaml
    - name: "Stackage 16.x"
      script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-16.yaml
      install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-16.yaml
    - name: "Stackage 15.x"
      script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-15.yaml
      install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-15.yaml
    - name: "Stackage 14.x"
      script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-14.yaml
      install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-14.yaml
    # - name: "Stackage 12.x"
    #   script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-12.yaml
    #   install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-12.yaml
    # - name: "Stackage 11.x"
    #   script: stack --no-terminal test --haddock --no-haddock-deps --stack-yaml stack-11.yaml
    #   install: stack --no-terminal --install-ghc test --only-dependencies --stack-yaml stack-11.yaml
