language: haskell
notifications:
    email:
        - cg.wowus.cg@gmail.com
    on_success: always
    on_failure: always
install:
    - cabal install --only-dependencies
    - cabal configure
    - cabal build
    - cabal haddock
