name = "fp"
version = "0.1.0"
description = "Haskell-style type classes and combinators."
licences = ["Apache-2.0"]
links = [{ title = "Source", href = "https://github.com/functora/functora.github.io/tree/master/pub/fp" }, {title = "Author", href = "https://21it.github.io"}]

[dependencies]
gleam_stdlib = "~> 0.27"

[dev-dependencies]
gleeunit = "~> 0.10"
