name:                generic-pretty-instances
version:             0.1.0.0
github:              "coingaming/src"
license:             BSD3
author:              "21it <21it@tuta.io>, Mikhail Prushinskiy <mprushinsky@gmail.com>, Artem Markov <drownbes@gmail.com>"
maintainer:          "21it <21it@tuta.io>, Mikhail Prushinskiy <mprushinsky@gmail.com>, Artem Markov <drownbes@gmail.com>"
copyright:           "2022 Yolo <hello@coingaming.io>"
synopsis:            "GenericPretty canonical instances"
description:         You can find documentation at <https://hackage.haskell.org/package/generic-pretty-instances>
homepage:            https://github.com/coingaming/src
category:            Text, Generics, Pretty Printer

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
# foundation
- base                >= 4.7 && < 5
- universum
# pretty stuff
- pretty
- pretty-simple
- GenericPretty
# instances for
- text
- vector
- bytestring
- base16-bytestring
- proto-lens
- proto-lens-runtime
- persistent
- time
- secp256k1-haskell   >= 0.6 && < 0.7
- case-insensitive


source-dirs:
- src

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- StrictData
- DeriveGeneric
- DerivingStrategies
- LambdaCase

ghc-options:
# For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
# Enable all warnings with -Weverything, then disable the ones we don’t care about
- -Weverything
- -Werror
- -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
- -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
- -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
- -Wno-all-missed-specialisations # See missed-specialisations
- -Wno-unsafe # Don’t use Safe Haskell warnings
- -Wno-safe # Don’t use Safe Haskell warnings
- -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
when:
  - condition: impl(ghc >= 8.10.7)
    ghc-options:
    - -Wno-unused-packages # Because of some proto-lens-runtime magic
    - -Wno-prepositive-qualified-module
    - -Wno-missing-safe-haskell-mode

library: {}

tests:
  generic-pretty-instances-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
